version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo Installing dependencies...
      - npm i

  build:
    commands:
      - echo Building project...
      # React/Vue: npm run build -> dist/ or build/ output
      # Angular: npm run build -- --configuration production
      - npm run build

  post_build:
    commands:
      - echo Build completed. Preparing artifacts...
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: |
    build